./format_solution ../instances/abz8 abz8.sol  flow_abz8.sol
./format_solution ../instances/dmu02 dmu02.sol flow_dmu02.sol
./format_solution ../instances/dmu33 dmu33.sol flow_dmu33.sol
./format_solution ../instances/dmu41 dmu41.sol flow_dmu41.sol
./format_solution ../instances/dmu59 dmu59.sol flow_dmu59.sol
./format_solution ../instances/ft20  ft20.sol  flow_ft20.sol
./format_solution ../instances/la31  la31.sol  flow_la31.sol
./format_solution ../instances/swv07 swv07.sol flow_swv07.sol
./format_solution ../instances/swv16 swv16.sol flow_swv16.sol
./format_solution ../instances/ta18  ta18.sol  flow_ta18.sol
./format_solution ../instances/ta27  ta27.sol  flow_ta27.sol
./format_solution ../instances/ta41  ta41.sol  flow_ta41.sol
./format_solution ../instances/yn02  yn02.sol  flow_yn02.sol