CC=g++
C=gcc
OPTIONS=-Wall -g3 -DGRB -std=c++11 -I/opt/gurobi800/linux64/include 
#-I/opt/gurobi752/linux64/include -L/opt/gurobi752/linux64/lib/ -lgurobi_c++ -lgurobi75 -lm `pkg-config --cflags cbc`
#-I/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/include/ `pkg-config --cflags cbc`

all:jssp

jssp:main.o Instance.o lp.o Flow.o Compact.o Kondili.o Fernando.o cgraph.o
	$(CC) $(OPTIONS) main.o Instance.o lp.o Flow.o Compact.o Kondili.o Fernando.o cgraph.o -L/opt/gurobi800/linux64/lib -lgurobi80 -lgurobi_c++ -o jssp 
#-lasan -lm `pkg-config --libs cbc` 

main.o:main.cpp 
	$(CC) $(OPTIONS) -c main.cpp -o main.o

Instance.o:src/Instance.cpp src/Instance.hpp
	$(CC) $(OPTIONS) -c src/Instance.cpp -o Instance.o

lp.o:src/lp.cpp src/lp.hpp src/lp.h
	$(CC) $(OPTIONS) -c src/lp.cpp -o lp.o

Compact.o:src/Compact.cpp src/Compact.hpp Instance.o lp.o
	$(CC) $(OPTIONS) -c src/Compact.cpp -o Compact.o

Kondili.o:src/Kondili.cpp src/Kondili.hpp Instance.o lp.o
	$(CC) $(OPTIONS) -c src/Kondili.cpp -o Kondili.o

Fernando.o:src/Fernando.cpp src/Fernando.hpp Instance.o lp.o
	$(CC) $(OPTIONS) -c src/Fernando.cpp -o Fernando.o

Flow.o:src/Flow_cuts.cpp src/Flow_cuts.hpp Instance.o lp.o
	$(CC) $(OPTIONS) -c src/Flow_cuts.cpp -o Flow.o

# Flow.o:src/Flow.cpp src/Flow.hpp Instance.o lp.o
# 	$(CC) $(OPTIONS) -c src/Flow.cpp -o Flow.o

cgraph.o:src/cgraph/cgraph.c src/cgraph/cgraph.h
	$(C) $(OPTIONS) -c src/cgraph/cgraph.c -o cgraph.o

clean:
	rm -rf *.o *~ jssp